### PR TITLE
Add code for a touch controller. Should work on iOS/Android

### PR DESCRIPTION
**Pull request by greggman**
This code is cribbed from http://github.com/greggman/hft-gamepad-api and
http://github.com/greggman/happyfuntimes

It doesn't seem to work in Edge at the moment.

### CODE REVIEW

**Comment by greggman** [comment]
Finally got around to getting this to build

You should only need 

```
index.html
controller/controller.js
controller/css/controller.cs
controller/assets/gear-icon.svg
```

I think

If you're a node guy and you want to mod it you can rebuild with

```
npm install   # installs needed packages in ./node_modules
./node_modules/grunt-cli/bin/grunt
```

That will build `controller/controller.js`

**Comment by lionello** [comment]
Awesome! I will upload it to the mcu tonight and test!

**Comment by lionello** [comment]
Darn, the .js appears to be too big; uploading it resets the device. I added gzip compression to the httpserver, but apparently 43Kb is still too big. Out of flash?

**Comment by greggman** [comment]
Changed it to use controller/controller.min.js. If you gzip that it's 25k.

I can try to rip stuff out after that if that doesn't work

**Comment by lionello** [comment]
Good move. I'll test tonight.

**Comment by lionello** [comment]
That did it! Just one typo: s/controller-min/controller.min/

**Pull request merged**
